
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A ABBR ACRONYM ARTICLE ASIDE AUDIO B BDO BLOCKQUOTE BODY BR BUTTON CAPTION CITE COL COLGROUP DATALIST DFN DIV DOCTYPE EM EMBED FIELDSET FOOTER FORM H1 H2 H3 H4 H5 H6 HEAD HEADER HR HTML IFRAME IMG INDENT INPUT KBD LABEL LEGEND LI LINK MARK META METER NAV OBJECT OL OPTGROUP OPTION OUTDENT OUTPUT P PRE PROGRESS Q RP RT RUBY SAMP SCRIPT SECTION SELECT SMALL SPAN STRONG STYLE SUB SUP TABLE TAG TBODY TD TEXTAREA TFOOT TH THEAD TIME TITLE TR UL VAR VIDEO WBR\n    doctype : DOCTYPE\n    \n    tag : TAG\n    '
    
_lr_action_items = {'DOCTYPE':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'doctype':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> doctype","S'",1,None,None,None),
  ('doctype -> DOCTYPE','doctype',1,'p_doctype','syntax.py',11),
  ('tag -> TAG','tag',1,'p_tag','syntax.py',18),
]
